name: Deploy React App to SpaceShips via FTP

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
    - name: Checkout repository # Clones the repository to the runner
      uses: actions/checkout@v4

    - name: Set up Node.js # Sets up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a stable Node.js version

    - name: Install dependencies # Installs project dependencies
      run: npm install

    - name: Build React app # Builds the React application for production
      run: npm run build

    - name: Deploy to FTP # Uses a third-party action for FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0 # Using a popular FTP deployment action
      with:
        server: ${{ secrets.SPACESHIPS_HOST }} # FTP server hostname from GitHub Secret
        username: ${{ secrets.SPACESHIPS_USER }} # FTP username from GitHub Secret
        password: ${{ secrets.SPACESHIPS_PASSWORD }} # FTP password from GitHub Secret
        port: ${{ secrets.SPACESHIPS_PORT }} # FTP port from GitHub Secret (should be 21)
        local-dir: './dist/' # The local directory to deploy (your built React app)
        remote-dir: '/home/mhbybxocvl/roboti.lat/public_html/' # The remote directory on your SpaceShips server
        # You MUST verify this remote-dir path. It should be the root of your roboti.lat domain.
        # Common paths are public_html/, www/, or a specific subdirectory like public_html/roboti.lat/
        # If roboti.lat points to a subfolder, you need to specify that here.
        # Example: remote-dir: '/home/mhbybx___afts.lv/Aina/public_html/roboti.lat/'
        # Make sure to include the trailing slash!
        state-name: .ftp-deploy-state.json # Stores deployment state to optimize future deployments
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .vscode/**