name: Deploy React App to SpaceShips

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
    - name: Checkout repository # Clones the repository to the runner
      uses: actions/checkout@v4

    - name: Set up Node.js # Sets up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a stable Node.js version

    - name: Install dependencies # Installs project dependencies
      run: npm install

    - name: Build React app # Builds the React application for production
      run: npm run build

    - name: Install SSH client # Installs sshpass for non-interactive SSH/rsync
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy via rsync over SSH # Deploys the built React app to SpaceShips
      env:
        SSH_HOST: ${{ secrets.SPACESHIPS_HOST }} # Hostname from GitHub Secret
        SSH_USER: ${{ secrets.SPACESHIPS_USER }} # Username from GitHub Secret
        SSH_PASS: ${{ secrets.SPACESHIPS_PASSWORD }} # Password from GitHub Secret
        # TARGET_DIR: /home/mhbybx___afts.lv/Aina/public_html/roboti.lat # Update this with the actual path on your SpaceShips server
        TARGET_DIR: /home/mhbybxocvl/roboti.lat/public_html/
      run: |
        # It's crucial to replace TARGET_DIR with the correct path on your SpaceShips server.
        # This path is where your website files should reside.
        # Common paths are public_html, www, or a specific subdirectory for your domain.
        # If your domain roboti.lat points to a specific directory, use that.
        # For now, I've put a common example. You might need to adjust this!
        echo "Deploying to $SSH_HOST as $SSH_USER into $TARGET_DIR"
        sshpass -p "$SSH_PASS" rsync -avz --delete dist/ "$SSH_USER"@"$SSH_HOST":"$TARGET_DIR"
        echo "Deployment complete!"